from app.models.spot import Spot

_RAW_SPOTS: list[dict] = [
    {
        "id": "denmark-hvide-sande",
        "country": "Denmark",
        "name": "Hvide Sande",
        "timezone": "Europe/Copenhagen",
        "lat": 56.004,
        "lon": 8.129,
        "shoreline_bearing_deg": 0,
        "offshore_sector_deg": {"start_deg": 45, "end_deg": 135},
        "preferred_wind_sector_deg": {"start_deg": 240, "end_deg": 20},
        "tide_windows": {"optimal": "mid", "ok": "all", "poor": "extreme chop"},
        "depth_profile": "medium",
        "spot_notes": "North Sea beach break with variable chop.",
    },
    {
        "id": "germany-fehmarn",
        "country": "Germany",
        "name": "Fehmarn",
        "timezone": "Europe/Berlin",
        "lat": 54.438,
        "lon": 11.193,
        "shoreline_bearing_deg": 320,
        "offshore_sector_deg": {"start_deg": 80, "end_deg": 170},
        "preferred_wind_sector_deg": {"start_deg": 250, "end_deg": 20},
        "tide_windows": {"optimal": "all", "ok": "all", "poor": "none"},
        "depth_profile": "shallow",
        "spot_notes": "Shallow areas and easy launch zones around the island.",
    },
    {
        "id": "italy-sicily",
        "country": "Italy",
        "name": "Sicily",
        "timezone": "Europe/Rome",
        "lat": 37.911,
        "lon": 12.489,
        "shoreline_bearing_deg": 10,
        "offshore_sector_deg": {"start_deg": 100, "end_deg": 180},
        "preferred_wind_sector_deg": {"start_deg": 250, "end_deg": 40},
        "tide_windows": {"optimal": "all", "ok": "all", "poor": "none"},
        "depth_profile": "medium",
        "spot_notes": "Mediterranean thermal and frontal wind mix.",
    },
    {
        "id": "morocco-essaouira",
        "country": "Morocco",
        "name": "Essaouira",
        "timezone": "Africa/Casablanca",
        "lat": 31.503,
        "lon": -9.761,
        "shoreline_bearing_deg": 10,
        "offshore_sector_deg": {"start_deg": 100, "end_deg": 180},
        "preferred_wind_sector_deg": {"start_deg": 260, "end_deg": 40},
        "tide_windows": {"optimal": "mid", "ok": "low-mid", "poor": "very high"},
        "depth_profile": "medium",
        "spot_notes": "Strong trades with shore break at higher tide.",
    },
    {
        "id": "morocco-dakhla",
        "country": "Morocco",
        "name": "Dakhla",
        "timezone": "Africa/Casablanca",
        "lat": 23.684,
        "lon": -15.944,
        "shoreline_bearing_deg": 340,
        "offshore_sector_deg": {"start_deg": 70, "end_deg": 150},
        "preferred_wind_sector_deg": {"start_deg": 240, "end_deg": 20},
        "tide_windows": {"optimal": "mid-high", "ok": "all", "poor": "very low"},
        "tide_penalties": [
            {
                "when": "below",
                "threshold_m": -0.2,
                "penalty_stars": 1.0,
                "reason": "low water shrinks the shallow lagoon and standing area",
            },
            {
                "when": "below",
                "threshold_m": -0.8,
                "penalty_stars": 1.5,
                "reason": "very low lagoon levels leave much less workable water in the lagoon",
            },
        ],
        "depth_profile": "shallow",
        "spot_notes": "Lagoon spot with large shallow sections.",
    },
    {
        "id": "spain-tarifa",
        "country": "Spain",
        "name": "Tarifa",
        "timezone": "Europe/Madrid",
        "lat": 36.013,
        "lon": -5.606,
        "shoreline_bearing_deg": 40,
        "offshore_sector_deg": {"start_deg": 280, "end_deg": 350},
        "preferred_wind_sector_deg": {"start_deg": 60, "end_deg": 220},
        "tide_windows": {"optimal": "mid", "ok": "all", "poor": "strong current"},
        "depth_profile": "medium",
        "spot_notes": "Levante can be gusty and offshore depending on beach.",
    },
    {
        "id": "spain-fuerteventura",
        "country": "Spain",
        "name": "Fuerteventura",
        "timezone": "Atlantic/Canary",
        "lat": 28.358,
        "lon": -14.054,
        "shoreline_bearing_deg": 20,
        "offshore_sector_deg": {"start_deg": 90, "end_deg": 180},
        "preferred_wind_sector_deg": {"start_deg": 250, "end_deg": 30},
        "tide_windows": {"optimal": "mid", "ok": "all", "poor": "shore break high"},
        "depth_profile": "medium",
        "spot_notes": "Atlantic island with wind acceleration effects.",
    },
    {
        "id": "sardinia-kite2sail",
        "country": "Sardinia",
        "name": "Kite2Sail",
        "timezone": "Europe/Rome",
        "lat": 41.088,
        "lon": 9.555,
        "shoreline_bearing_deg": 20,
        "offshore_sector_deg": {"start_deg": 100, "end_deg": 190},
        "preferred_wind_sector_deg": {"start_deg": 250, "end_deg": 30},
        "tide_windows": {"optimal": "all", "ok": "all", "poor": "none"},
        "depth_profile": "deep",
        "spot_notes": "Boat-based sessions depending on route and island shelter.",
    },
    {
        "id": "greece-kos",
        "country": "Greece",
        "name": "Kos",
        "timezone": "Europe/Athens",
        "lat": 36.893,
        "lon": 27.288,
        "shoreline_bearing_deg": 350,
        "offshore_sector_deg": {"start_deg": 60, "end_deg": 140},
        "preferred_wind_sector_deg": {"start_deg": 260, "end_deg": 20},
        "tide_windows": {"optimal": "all", "ok": "all", "poor": "none"},
        "depth_profile": "medium",
        "spot_notes": "Meltemi-driven winds with chop.",
    },
    {
        "id": "egypt-el-gouna",
        "country": "Egypt",
        "name": "El Gouna",
        "timezone": "Africa/Cairo",
        "lat": 27.394,
        "lon": 33.678,
        "shoreline_bearing_deg": 335,
        "offshore_sector_deg": {"start_deg": 70, "end_deg": 140},
        "preferred_wind_sector_deg": {"start_deg": 260, "end_deg": 20},
        "tide_windows": {"optimal": "mid-high", "ok": "all", "poor": "very low"},
        "depth_profile": "shallow",
        "spot_notes": "Lagoon sections can become shallow at low water.",
    },
    {
        "id": "egypt-seahorse-bay",
        "country": "Egypt",
        "name": "Seahorse Bay",
        "timezone": "Africa/Cairo",
        "lat": 27.251,
        "lon": 33.835,
        "shoreline_bearing_deg": 345,
        "offshore_sector_deg": {"start_deg": 75, "end_deg": 145},
        "preferred_wind_sector_deg": {"start_deg": 255, "end_deg": 25},
        "tide_windows": {"optimal": "mid-high", "ok": "all", "poor": "very low"},
        "tide_penalties": [
            {
                "when": "below",
                "threshold_m": 0.1,
                "penalty_stars": 1.0,
                "reason": "low water exposes coral and makes the launch zone very shallow",
            },
            {
                "when": "below",
                "threshold_m": -0.4,
                "penalty_stars": 1.5,
                "reason": "very low water heavily reduces rideable depth over the reef flat",
            },
        ],
        "depth_profile": "shallow",
        "spot_notes": "Flat-water sections and shallow reef/coral areas at low tide.",
    },
    {
        "id": "tunisia-djerba",
        "country": "Tunisia",
        "name": "Djerba",
        "timezone": "Africa/Tunis",
        "lat": 33.742,
        "lon": 10.966,
        "shoreline_bearing_deg": 10,
        "offshore_sector_deg": {"start_deg": 100, "end_deg": 180},
        "preferred_wind_sector_deg": {"start_deg": 250, "end_deg": 30},
        "tide_windows": {"optimal": "all", "ok": "all", "poor": "none"},
        "depth_profile": "shallow",
        "spot_notes": "Flat-water lagoons in parts of the island.",
    },
    {
        "id": "cape-verde-sal",
        "country": "Cape Verde",
        "name": "Sal",
        "timezone": "Atlantic/Cape_Verde",
        "lat": 16.733,
        "lon": -22.936,
        "shoreline_bearing_deg": 15,
        "offshore_sector_deg": {"start_deg": 95, "end_deg": 175},
        "preferred_wind_sector_deg": {"start_deg": 250, "end_deg": 30},
        "tide_windows": {"optimal": "mid", "ok": "all", "poor": "heavy shore break"},
        "depth_profile": "deep",
        "spot_notes": "Open ocean swell at exposed beaches.",
    },
    {
        "id": "brazil-tatajuba",
        "country": "Brazil",
        "name": "Tatajuba",
        "timezone": "America/Fortaleza",
        "lat": -2.896,
        "lon": -40.278,
        "shoreline_bearing_deg": 340,
        "offshore_sector_deg": {"start_deg": 70, "end_deg": 150},
        "preferred_wind_sector_deg": {"start_deg": 240, "end_deg": 20},
        "tide_windows": {"optimal": "mid-high", "ok": "all", "poor": "very low"},
        "depth_profile": "shallow",
        "spot_notes": "Flat-water lagoons and downwind routes.",
    },
    {
        "id": "brazil-prea",
        "country": "Brazil",
        "name": "Prea",
        "timezone": "America/Fortaleza",
        "lat": -2.792,
        "lon": -40.508,
        "shoreline_bearing_deg": 350,
        "offshore_sector_deg": {"start_deg": 80, "end_deg": 160},
        "preferred_wind_sector_deg": {"start_deg": 245, "end_deg": 25},
        "tide_windows": {"optimal": "mid", "ok": "all", "poor": "strong shore break"},
        "depth_profile": "medium",
        "spot_notes": "Consistent trades, stronger chop in open water.",
    },
    {
        "id": "brazil-jericoacoara",
        "country": "Brazil",
        "name": "Jericoacoara",
        "timezone": "America/Fortaleza",
        "lat": -2.793,
        "lon": -40.515,
        "shoreline_bearing_deg": 350,
        "offshore_sector_deg": {"start_deg": 80, "end_deg": 160},
        "preferred_wind_sector_deg": {"start_deg": 245, "end_deg": 25},
        "tide_windows": {"optimal": "mid", "ok": "all", "poor": "strong shore break"},
        "depth_profile": "medium",
        "spot_notes": "Wave and freeride conditions around the bay.",
    },
    {
        "id": "brazil-kite-safari",
        "country": "Brazil",
        "name": "Kite Safari",
        "timezone": "America/Fortaleza",
        "lat": -2.868,
        "lon": -40.143,
        "shoreline_bearing_deg": 350,
        "offshore_sector_deg": {"start_deg": 80, "end_deg": 160},
        "preferred_wind_sector_deg": {"start_deg": 245, "end_deg": 25},
        "tide_windows": {"optimal": "mid", "ok": "all", "poor": "spot-dependent"},
        "depth_profile": "mixed",
        "spot_notes": "Route product with multiple lagoon and ocean stops.",
    },
    {
        "id": "panama-punta-chame",
        "country": "Panama",
        "name": "Punta Chame",
        "timezone": "America/Panama",
        "lat": 8.646,
        "lon": -79.878,
        "shoreline_bearing_deg": 300,
        "offshore_sector_deg": {"start_deg": 20, "end_deg": 110},
        "preferred_wind_sector_deg": {"start_deg": 200, "end_deg": 340},
        "tide_windows": {"optimal": "mid-high", "ok": "all", "poor": "very low"},
        "tide_penalties": [
            {
                "when": "above",
                "threshold_m": 1.2,
                "penalty_stars": 0.5,
                "reason": "at high spring tides the beach can disappear for part of the session",
            }
        ],
        "depth_profile": "shallow",
        "spot_notes": "Large tidal flats can dry out at very low tide.",
    },
    {
        "id": "zanzibar-jambiani",
        "country": "Zanzibar",
        "name": "Jambiani",
        "timezone": "Africa/Dar_es_Salaam",
        "lat": -6.313,
        "lon": 39.55,
        "shoreline_bearing_deg": 15,
        "offshore_sector_deg": {"start_deg": 100, "end_deg": 180},
        "preferred_wind_sector_deg": {"start_deg": 250, "end_deg": 30},
        "tide_windows": {"optimal": "mid-high", "ok": "all", "poor": "very low"},
        "tide_penalties": [
            {
                "when": "below",
                "threshold_m": 0.0,
                "penalty_stars": 0.5,
                "reason": "very low water means a long walk across the reef flat before riding",
            },
            {
                "when": "above",
                "threshold_m": 1.0,
                "penalty_stars": 1.0,
                "reason": "at high tide the inner lagoon gets harder and more technical",
            },
        ],
        "depth_profile": "shallow",
        "spot_notes": "Reef lagoon, strong tide influence and long walks at low tide.",
    },
    {
        "id": "kenya-mwazaro-beach",
        "country": "Kenya",
        "name": "Mwazaro Beach",
        "timezone": "Africa/Nairobi",
        "lat": -4.642,
        "lon": 39.386,
        "shoreline_bearing_deg": 20,
        "offshore_sector_deg": {"start_deg": 105, "end_deg": 185},
        "preferred_wind_sector_deg": {"start_deg": 250, "end_deg": 35},
        "tide_windows": {"optimal": "mid-high", "ok": "all", "poor": "very low"},
        "min_safe_tide_m": 0.3,
        "depth_profile": "shallow",
        "spot_notes": "Lagoon and reef setup with tidal current changes.",
    },
    {
        "id": "south-africa-cape-town",
        "country": "South Africa",
        "name": "Cape Town",
        "timezone": "Africa/Johannesburg",
        "lat": -33.925,
        "lon": 18.424,
        "shoreline_bearing_deg": 340,
        "offshore_sector_deg": {"start_deg": 55, "end_deg": 130},
        "preferred_wind_sector_deg": {"start_deg": 240, "end_deg": 20},
        "tide_windows": {"optimal": "mid", "ok": "all", "poor": "heavy shore break"},
        "depth_profile": "deep",
        "spot_notes": "Strong winds, cold water, and powerful swell.",
    },
    {
        "id": "sri-lanka-kalpitiya",
        "country": "Sri Lanka",
        "name": "Kalpitiya",
        "timezone": "Asia/Colombo",
        "lat": 8.232,
        "lon": 79.756,
        "shoreline_bearing_deg": 345,
        "offshore_sector_deg": {"start_deg": 75, "end_deg": 150},
        "preferred_wind_sector_deg": {"start_deg": 245, "end_deg": 20},
        "tide_windows": {"optimal": "mid-high", "ok": "all", "poor": "very low"},
        "min_safe_tide_m": 0.25,
        "depth_profile": "shallow",
        "spot_notes": "Lagoon and ocean side options with seasonal monsoon shifts.",
    },
]

SPOTS: list[Spot] = [Spot.model_validate(raw) for raw in _RAW_SPOTS]
SPOTS_BY_ID: dict[str, Spot] = {spot.id: spot for spot in SPOTS}


def list_spots() -> list[Spot]:
    return SPOTS


def get_spot(spot_id: str) -> Spot | None:
    return SPOTS_BY_ID.get(spot_id)
